version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    ports:
      - "10001-10099:10001-10099"
    volumes:
      - ./config.json:/etc/v2ray/config.json
    command: ["run", "-config=/etc/v2ray/config.json"]
    restart: always
